Models/URL.cs
namespace webdev.Models
{
    public class URL
    {
        public int Id { get;set; }
        public string Address { get; set; }
        public string HideAddress { get; set; }
    }
}

Controllers/URLController.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using webdev.Interfaces;
using webdev.Models;

namespace webdev.Controllers
{
    public class URLController : Controller
    {
        private IURLsRepository _repository;
        
        public URLController(IURLsRepository URLsRepository)
        {
            _repository = URLsRepository;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var URLs = _repository.GetURLs();
            return View(URLs);
        }

        [HttpPost]
        public IActionResult Create(URL URL)
        {
            _repository.AddURL(URL);
            return Redirect("Index");
        }

        [HttpGet]
        public IActionResult Delete(URL URL)
        {
            _repository.Delete(URL);
            return Redirect("Index");
        }


        [HttpGet]
        public IActionResult Edit(URL URL) 
        {
            return View(URL);
        }
        
        [HttpPost]
        public IActionResult Update(URL URL) 
        {
            _repository.Update(URL);
            return Redirect("Index");
        }
    }
}

Views/URL/Edit.cshtml
@model webdev.Models.URL
<div>
    <table>
        <tr>
            <td><strong>@Html.DisplayNameFor(model => Model.Address):</strong></td>
            <td>@Html.DisplayFor(model => Model.Address),</td>
        </tr>
    </table>
</div>

<div>
    @using (Html.BeginForm("Update", "URL", FormMethod.Post))
    {
        <input type="text" name="Address" placeholder="Address"/> <br/>
        @Html.HiddenFor(model => Model.Id)
        <button type="submit">Zmień</button>
    }
</div>
     

Views/URL/Index.cshtml
@model List<webdev.Models.URL>
<div>
    @using (Html.BeginForm("Create", "URL", FormMethod.Post))
    {
        
        <input type="text" name="Address" placeholder="Address"/> <br/>
        <button type="submit">Dodaj</button>
    }
</div>  
<div>
    <table>
        @foreach(var item in Model) {
            <tr>
                <td><strong>@Html.DisplayNameFor(model => item.Address):</strong></td>
                <td>@Html.DisplayFor(model => item.Address),</td>
                <td>|| @Html.ActionLink(item.HideAddress, "SendToURL", "Link", new { address=item.Address }, new  {target="_blank" })</td>
                <td>| @Html.ActionLink("Usuń", "Delete", "URL", item)</td>
                <td>| @Html.ActionLink("Zmień", "Edit", "URL", item)</td>
               
            </tr>
        }
    </table>
</div>